name: project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - abseil-cpp=20210324.0=h9c3ff4c_0
  - absl-py=0.12.0=pyhd8ed1ab_0
  - alsa-lib=1.2.3=h516909a_0
  - altair=4.1.0=py_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py37h5e8e339_2
  - arrow-cpp=3.0.0=py37ha76e1b8_12_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=21.2.0=pyhd8ed1ab_0
  - audioread=2.1.9=py37h89c1867_0
  - aws-c-cal=0.5.10=h95a6274_1
  - aws-c-common=0.6.2=h7f98852_0
  - aws-c-event-stream=0.2.7=h55ff71c_10
  - aws-c-io=0.10.2=h2cf07f8_2
  - aws-checksums=0.1.11=ha31a3da_7
  - aws-sdk-cpp=1.8.186=hb4091e7_3
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - base58=2.1.0=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - boto3=1.17.93=pyhd8ed1ab_0
  - botocore=1.20.93=pyhd8ed1ab_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.2=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - catboost=0.26=py37h89c1867_0
  - certifi=2021.5.30=py37h89c1867_0
  - cffi=1.14.5=py37hc58025e_0
  - chardet=4.0.0=py37h89c1867_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py37h5d9358c_0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_1
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - eli5=0.11.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3.1=hca11adc_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.19.8.1=h0b5b191_1005
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.17=pyhd8ed1ab_0
  - glog=0.5.0=h48cff8f_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.47.2=h85b4f2f_0
  - grpc-cpp=1.37.1=h36de60a_0
  - grpcio=1.38.0=py37hb27c1af_0
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - h5py=3.2.1=nompi_py37ha3df211_100
  - harfbuzz=2.8.1=h83ec7ef_0
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - importlib-metadata=4.5.0=py37h89c1867_0
  - ipykernel=5.5.5=py37h085eea5_0
  - ipython=7.24.1=py37h085eea5_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jack=1.9.18=hfd4fe87_1001
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py37h2527ec5_1
  - krb5=1.19.1=hcc1bbae_0
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcurl=7.77.0=h2574ce0_0
  - libdb=6.2.32=h9c3ff4c_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgd=2.3.2=h78a0170_0
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.3=h3e27bee_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.8=h780b84a_0
  - librosa=0.8.1=pyhd8ed1ab_0
  - librsvg=2.50.7=hc3c00ef_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libthrift=0.14.1=he6d91bd_1
  - libtiff=4.2.0=h85742a9_0
  - libtool=2.4.6=h58526e2_1007
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxgboost=1.4.0=h9c3ff4c_0
  - libxml2=2.9.12=h72842e0_0
  - llvmlite=0.36.0=py37h9d7f4d0_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py37h5e8e339_0
  - matplotlib-base=3.4.2=py37hdd32ed1_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py37h5e8e339_1003
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - notebook=6.4.0=pyha770c72_0
  - numba=0.53.1=py37hb11d6e1_1
  - numpy=1.20.3=py37h038b26d_1
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h7f98852_0
  - orc=1.6.7=heec2584_1
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py37h219a48f_0
  - pandoc=2.14.0.2=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - pango=1.48.5=hb8ff022_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=6.2.1=py37h6b7be26_0
  - pip=22.0.2
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - portaudio=19.6.0=h7b6447c_4
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - protobuf=3.15.8=py37hcd2ae1e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-xgboost=1.4.0=py37h89c1867_0
  - pyarrow=3.0.0=py37he2832ee_12_cpu
  - pyaudio=0.2.11=py37h8f50634_1002
  - pycparser=2.20=pyh9f0ad1d_2
  - pydeck=0.6.2=pyh44b312d_0
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h5e8e339_2
  - pysocks=1.7.1=py37h89c1867_3
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.7.10=h12debd9_4
  - python-dateutil=2.8.1=py_0
  - python-graphviz=0.16=pyh243d235_2
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py37h5e8e339_0
  - pyzmq=22.1.0=py37h336d617_0
  - re2=2021.04.01=h9c3ff4c_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - resampy=0.2.2=py_0
  - s2n=1.0.10=h9b69904_0
  - s3transfer=0.4.2=pyhd8ed1ab_0
  - scikit-learn=0.24.2=py37h18a542f_0
  - scipy=1.6.3=py37h29e03ee_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py37h06a4308_0
  - singledispatch=3.6.1=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.35.4=hdfb4753_0
  - statsmodels=0.12.2=py37h902c9e0_0
  - streamlit=0.82.0=pyhd8ed1ab_1
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tensorboard=1.14.0=py37_0
  - tensorflow=1.14.0=h4531e10_0
  - tensorflow-base=1.14.0=py37h4531e10_0
  - tensorflow-estimator=1.14.0=py37h5ca1d4c_0
  - termcolor=1.1.0=py_2
  - terminado=0.10.1=py37h89c1867_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py37h5e8e339_1
  - traitlets=5.0.5=py_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzlocal=2.1=pyh9f0ad1d_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - validators=0.18.2=pyhd3deb0d_0
  - watchdog=2.1.2=py37h89c1867_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37h89c1867_4
  - wrapt=1.12.1=py37h5e8e339_3
  - x264=1!161.3030=h7f98852_0
  - xgboost=1.4.0=py37h89c1867_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - youtube-dl=2021.6.6=py37h89c1867_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - nightcore==1.1.0
    - pydub==0.23.1
prefix: /home/akshat/anaconda3/envs/project
